spring:
  application:
    name: sign-language-transport-backend
  
  profiles:
    active: dev
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Logging
logging:
  level:
    com.capstone: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

# External API Configuration
external:
  korail:
    base-url: https://api.railway.co.kr
    api-key: ${KORAIL_API_KEY:your-api-key-here}
  
  kakao:
    base-url: https://kapi.kakao.com
    api-key: ${KAKAO_API_KEY:your-kakao-api-key-here}

# QR Code Configuration
qr:
  size: 300
  format: PNG
